### ISSUE TITLE
Typings: File splitting

### ISSUE THREAD

**Issue by bsian03** [Khaazz/AxonCore#58]
Creating just so we can keep track of stuff

File structure:
```
AxonCore
| typings
| | Definitions and subdefinitions
| | libraries
| | | Eris.ts
| | | DiscordJS.ts
| | | Detritus.ts
| | | index.ts (read off this file)
| | | Normal library typings - Includes library specific enums - default to contain Eris enums
| | misc
| | | interfaces.ts
| | | enums.ts - Only AxonEnums and DiscordEnums
```

I'll open and link PR once this is ready

**Comment by bsian03** [comment]
Obviously Detritus library specific typings won't be included as of yet

**Comment by Khaazz** [comment]
The PR closing this issue will also includes:
- dynamic typings (dynamically link with eris / discordjs typings)
Via CLI (`bin` property in package.json)
eg: `yarn library <lib>`.
- CI update to lint all the typings folder
